In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("data/all_cities.csv")

In [3]:
city_localities = (
    df.groupby('city')['locality']
    .unique()
    .apply(list)
    .to_dict()
)

print(city_localities)

{'ahmedabad': ['Shela', 'Bopal', 'Ghuma', 'Jagatpur', 'Chandlodia', 'Vishala', 'Gota', 'Vaishno Devi Circle', 'Shantigram', 'Bodakdev', 'Vasna', 'Iscon Ambli Road', 'Chandkheda', 'South Bopal', 'Zundal', 'Jodhpur', 'Prahlad Nagar', 'Nirnay Nagar', 'Paldi', 'Science City', 'Ambawadi', 'Satellite', 'Sola', 'Shilaj', 'Tragad', 'Ramdev Nagar', 'Thaltej', 'Naranpura', 'Chharodi', 'Makarba', 'Vastrapur', 'Motera', 'Shyamal', 'Ognaj', 'Maninagar', 'Ghatlodiya', 'Science Park', 'Ellisbridge', 'University Area', 'Bhat', 'Memnagar', 'Vastral', 'Bilasiya', 'Ambli', 'Vikram Nagar', 'Hanspura', 'Shantipura', 'Nana Chiloda', 'Narolgam', 'GIDC Naroda', 'New Ranip', 'Odhav', 'Bhadaj', 'Navrangpura', 'Vejalpur', 'Isanpur', 'Shahibaug', 'Sarkhej', 'Chanakyapuri', 'Nava Naroda', 'Hansol', 'Navarangpura', 'New Maninagar', 'Sanand', 'Gurukul', 'Lambha', 'Koteshwar', 'Nikol', 'Vinzol', 'Naroda', 'Bavla', 'Vatva', 'Ujala Circle', 'Ranip', 'Changodar', 'Gulbai Tekra', 'Juhapura', 'Usmanpura', 'Dholera', 'Daskroi', 'Mahadev Nagar', 'Old Wadaj', 'Thakkarbapa Nagar', 'Sanathal', 'Ghodasar', 'Khokhra', 'Godhavi', 'Noble Nagar Tenament', 'Nava Vadaj', 'Ramol', 'Sabarmati', 'Jodhpur Tekra', 'Hathijan', 'Acher', 'Khoraj', 'Sanidhya', 'Jivrajpark', 'Kathwada', 'Amraiwadi', 'Manipur', 'Jasodanagr', 'Aslali', 'Moraiya', 'Enasan', 'Saraspur', 'Vinobanagar', 'Krishna Nagar Society', 'Jaldhara-3', 'Saijpur Bogha', 'Dholka', 'Bapunagar', 'Kotarpur', 'Raska', 'Kasindra', 'Hansalpur Becharaji', 'Kuber Nagar', 'Hatkeshwar', 'Bakrol Bujrang', 'Ayojan Nagar', 'Lilapur', 'Khadia', 'Kankaria', 'Hebatpur', 'Rambagh', 'Meghani Nagar', 'Janta Nagar', 'Gokuldham', 'Kuha', 'Keshav Nagar', 'Navjivan', 'Dani Limda', 'India Colony', 'Geratpur', 'GIDC Vatwa', 'Shahpur', 'Asarwa', 'Dudeshwar', 'Behrampura', 'Kalupur', 'Sardar Colony', 'Bhadra', 'Khanpur', 'Pipan', 'Devdholera', 'Daran', 'Gamdi', 'Lapkaman', 'Vasna Iyava', 'Gandhinagar', 'Telav', 'Chekhla', 'Chhabasar', 'Kolat', 'Rakhial'], 'bengaluru': ['Balagere', 'Chokkanahalli', 'Gunjur Palya', 'Kambipura', 'Chikkakannalli', 'V. Kallahalli', 'Electronic City', 'Yadavanahalli', 'Gummanahalli', 'Kadagrahara', 'Anantapura', 'Dommasandra', 'Electronic City Phase 2', 'Chikkanagamangala', 'Devinagar', 'Kumbalgodu', 'Kalkere', 'Varthur', 'Kaggadasapura', 'Bedarahalli', 'Thanisandra', 'Boodihal', 'Murugeshpalya', 'Richards Town', 'K R Puram', 'Vasanth Nagar', 'Hosahalli', 'Byatarayanapura', 'Halasahalli', 'Doddakannelli', 'Kadugodi', 'Uttarahalli -Manavarthekaval', 'Begur', 'Bhoganhalli', 'Byrathi', 'Chikkagubbi Village', 'Vakil Garden City', 'Rayasandra', 'Kannamangala - Whitefield Hoskote Road', 'Sarjapur', 'Bellandur', 'Kalyan Nagar', 'New Tippasandra', 'Kumaraswamy Layout', 'Cox Town', 'Narayanapura', 'Varanasi', 'Budigere Cross', 'RR Nagar', 'Hoodi', 'Visthar', 'Thurahalli', 'Rajajinagar', 'Panathur', 'Kasavanahalli', 'Medahalli', 'C V Raman Nagar', 'Lingadheeranahalli', 'HSR Layout', 'Koramangala', 'Kasturi Nagar', 'Sheshadripuram', 'Horamavu', 'Hebbal Kempapura', 'Bilekahalli', 'NRI Layout', 'Shivaji Nagar', 'Agrahara Layout', 'Rustam Bagh Layout', 'Mallasandra', 'Arakere', 'Talaghattapura', 'Subramanyapura', 'Gunjur Village', 'Munnekollal', 'Yelahanka New Town', 'Vajarahalli', 'Basavanagudi', 'Mahadevapura', 'Hulimavu', 'Jyotipuram', 'Mahalakshmi Layout', 'Padmanabhanagar', 'Gottigere', 'S.G. Palya', 'Cooke Town', 'Kodathi', 'JP Nagar', 'Whitefield', 'Puttenahalli', 'Indira Nagar', 'Banaswadi', 'Nagarbhavi', 'Cheemasandra', 'Banashankari Temple Ward', 'Yeswanthpur', 'Dooravani Nagar', 'Basavanagar', 'Frazer Town', 'Hosakerehalli', 'Jnana Ganga Nagar', 'Yelahanka', 'RMV Extension Stage 2', 'Bommanahalli', 'Kannuru', 'Akshayanagar', 'HBR Layout', 'Kengeri', 'Kodagalahatti', 'Huvinane', 'Kadugodi Plantation', 'Nagareshwara - Nagenahalli', 'Benson Town', 'Kodipur', 'Armane Nagar', 'Essel Gardens', 'Ramanashree California Gardens Layout', 'Richmond Town', 'Kanakapura', 'Amrutahalli', 'Singasandra', 'Jakkur', 'Kogilu', 'Nagavara', 'Bommenahalli', 'Virupakshapura', 'Doddanekundi', 'Bikasipura', 'GB Palya', 'Hallehalli', 'Doddakallasandra', 'Sultanpalya', 'K Channasandra', 'Tirumanahalli', 'Sompura', 'Anchepalya', 'Sahakara Nagar', 'Vijayanagar', 'Jagajeevanram Nagar', 'Battarahalli', 'Halasuru', 'Hosur', 'Nehru Nagar', 'Anekal', 'Kempegowda Nagar', 'Parappana Agrahara', 'Jalahalli', 'Sanjaynagar', 'R.K. Hegde Nagar', 'Kadubeesanahalli', 'Brookefield', 'Ramamurthy Nagar', 'Thirumagondanahalli', 'Kammanahalli', 'Hongasandra', 'Hebbal', 'Jeevan Bima Nagar', 'Vidyaranyapura', 'Chandrasekarapura', 'Kyalasanahalli', 'Harlur', 'Choodasandra', 'Marathahalli', 'Chandapura', 'Kudlu Gate', 'BTM Layout', 'Bommasandra', 'Kudlu', 'Kothanur', 'Malleswaram', 'Jayanagar', 'Nagondanahalli', 'New Baiyyappanahalli', 'Sanjeevini Nagar', 'Reliaable Tranquil Layout', 'Thirupalya', 'Goravigere', 'Binnipete', 'Devarachikkana Halli', 'Yelachenahalli', 'Konanakunte', 'Doddabommasandra', 'Annapurneshwari Nagar', 'Kalena Agrahara', 'Carmelaram', 'Hoskote', 'Kaggalipura', 'Devanahalli', 'Attibele', 'T Dasarahalli', 'Shanti Nagar', 'Bidaraguppe', 'Chansandra', 'Chikkabana Halli', 'Bengaluru North', 'Sampangi Rama Nagar', 'Chikkasanne', 'Singapura', 'Thirumalashettyhally', 'Hennur', 'Kodipalya', 'Thindlu', 'Madhura Nagar', 'Chikkadunnasandra', 'Samethanahalli', 'Gattahalli', 'KPC Layout', 'Katamnallur', 'Sampigehalli', 'Bidare Agraha', 'Konadasapura', 'Muneshwara Nagar', 'Sannatammanahalli', 'Basapura', 'Baiyappanahalli', 'BEML Cooperative Society Layout', 'Bendiganahalli', 'Chambenahalli', 'Yamare', 'Huvinayakanahalli', 'B.Hosahalli', 'Mangammanapalya', 'Boovanahalli', 'Victoria Layout', 'Hunasamaranahalli', 'Navarathna Agrahara', 'Kolur', 'Gunjur', 'Raghuvanahalli', 'Jigani', 'Thattanahalli', 'Suradhenupura', 'Chikkabanavara', 'Vittasandra', 'Kartik Nagar', 'Kachamaranahalli', 'Kaikondrahalli', 'Kodigehalli', 'Nagegowdanapalya', 'Vignana Kendra', 'Kaval Bairasandra', 'Srinivaspura', 'Banashankari', 'Thyvakanahally', 'Chamrajpet', 'Aavalahalli', 'Chikkalasandra', 'Tejaswini Nagar', 'Hemmigepura', 'Somasundarapalya', 'Kuthaganahalli', 'Margondanahalli', 'Kariyana Palya', 'Marsur', 'Abbigere', 'Harohalli', 'Kengeri Satellite Town', 'Junnasandra', 'Chandra Layout Stage 1', 'Volagerekallahalli', 'Gonighattapura', 'Adugodi', 'Jayamahal', 'Sivanchetti Gardens', 'ISRO Layout', 'Mullur', 'BTM Layout 2nd Stage', 'Jalahalli West', 'Bangalore City Municipal Corporation Layout', 'Domlur Layout', 'Kithaganur Village', 'Yadiyuru', 'Geddalahalli', 'Uttarahalli Hobli', 'Huskur', 'Kadugodi Industrial Area', 'Channanayakanapalya', 'Madivala', 'Mavalli', 'Mathikere', 'Doddagattiganabbe', 'Devara Jeevanahalli', 'RT Nagar', 'Ganganagar', 'Byagadadhenahalli', 'Ullalu', 'Kasuvanahalli', 'Chikkadasarahalli', 'Sunkalpalya', 'Lakshmisagara', 'Kacharakanahalli', 'Kamakshipalya', 'Prakruthi Township', 'Mahalakshmipuram', 'Gantiganahalli', 'Bagalakunte', 'Kodihalli', 'Srirampuram', 'Bileshivale', 'Chandra Layout Extension', 'Mailasandra', 'Bagalur', 'Naganaikanahalli', 'Agrahara', 'Bychapura', 'Bennigana Halli', 'Udayagiri', 'Jigala', 'Channahalli', 'Chikkabellandur', 'Chinnapanna Halli', 'Dasanayakanahalli', 'Sarvagnanagar', 'Kithaganur Colony', 'Gopasandra', 'Mallathahalli', 'Lingarajapuram', 'Yelachanayakanapura', 'Kattigenahalli', 'Ramanagara', 'Basaveshwara Nagar', 'Sunkadakatte', 'Ittangur', 'Kothnur Narayanapura', 'Bisnahalli', 'Doddabele', 'Dasanapura', 'Anjanapura Township', 'S.Medihalli', 'Hullahalli', 'Basavanapura', 'Bharat Nagar', 'Anjanapura', 'Banashankari 6th Stage 4th Block', 'SMV Layout', 'Ashok Nagar', 'Kempalingapura', 'Doddabidrakallu', 'Nagadevana Halli', 'Andrahalli', 'Vidyamanya Nagar', 'Gnana Bharathi', 'Ullal Uppanagar', 'Vishveshwaraya Nagar', 'Chikkabettahalli', 'Attiguppe', 'Thammenahalli Village', 'Thathaguni', 'Byadralli', 'Gangondanahalli', 'Judicial Layout', 'Nelamangala', 'Kadabagere', 'Bendre Nagar', 'Kithiganur', 'Ckikkakammana Halli', 'Hosahalli Gollarapalya', 'Vaderamanchana Halli', 'Tunganagara', 'Hancharahalli Village', 'Chikkagubbi', 'Koppa Gate', 'Manganahalli', 'Kachohalli', 'Pavamanapura', 'ITI Layout', 'Kurubarahalli', 'Thotada Guddadhalli Village', 'Maruthi Nagar', 'Vimanapura', 'Neraluru', 'Bidarahalli', 'Anagalapura', 'Ejipura', 'Syndicate Bank Employees Housing Society Layout', 'Hebbagodi', 'Varadanahalli', 'Deepanjali Nagar', 'Nadaprabhu Kempegowda layout', 'Kada Agrahara', 'Tigalarapalya', 'Seegehalli', 'Dodda Gubbi', 'Rukmini Nagar', 'Kariobanahalli', 'Soundarya Layout', 'Kammassandra', 'D Group Employees Layout', 'Yelahanka Satellite Town', 'HAL', 'Rajanukunte', 'Kamala Nagar', 'Sidedahalli', 'Kammasandra', 'Aduru', 'Laggere', 'Hirandahalli', 'Machohalli', 'Mylasandra', 'Bhyraveshwara Nagar', 'Halasahalli Thippasandra', 'Rampura', 'S.Bingipura', 'Arasinakunte', 'Ramasandra', 'Kathirguppe', 'Madanayakahalli', 'Virupakshipura', 'Wilson Garden', 'Banashankari 6th Stage 6th Block', 'Totadaguddadahalli', 'Maruthi Sevanagar', 'J C Nager', 'Vibhutipura', 'Panduranga Nagar', 'Bapuji Nagar', 'Mandur', 'Peenya', 'Thirumanahalli', 'Guguttahalli', 'Azad Nagar', 'Mugalur', 'Byalahalli', 'Thathnur Plantation', 'Magadi', 'CK Palya', 'Maragondanahalli', 'Bodanahosahalli', 'Nimbekaipura', 'Doddanagamangala', 'Hesaraghatta', 'Harapanahalli', 'Nandini Layout', 'Dobbsapet', 'Dombarahalli', 'Doddadunnasandra', 'Doddaballapura', 'Veerasagara', 'Kengeri Hobli', 'Attibele Industrial Area', 'Bhimenahalli', 'Bheemanakuppe', 'Chikballapur District', 'Mitganahalli', 'Varadharaja Nagar', 'Ramnagara', 'Sathnur', 'Kadugondanahalli', 'Srinivaspur', 'Chikkabidarakallu', 'Dasarahalli', 'Singanayakanahalli', 'Bannerughatta', 'T.B Cross', 'Hejjala', 'Sulikunte', 'Jalahalli East', 'Kundana', 'Aranakuppe', 'Chikkajala', 'Bandaramanahalli', 'Kodalagurki', 'Sanne Amanikere', 'Bendiganahalli Anekal Taluka', 'Tyayakana Halli', 'Ramohalli', 'Bidadi', 'Panditana Agrahara', 'Kumbaranahalli', 'Bettahalsoor', 'Shringaripura', 'Kotiganahalli', 'Lakkondahalli', 'Shettigere', 'Gudighattanahalli', 'Addevishvanathapura', 'Kammasandra Agrahara', 'Pujanahalli', 'Arenur', 'Hampa Pura', 'Kakaramanahalli', 'Kolar', 'Byalalu', 'Sreeramanahalli', 'Dodda Aalada Mara', 'Doddakammanahalli', 'Suragajakkanahalli', 'Marasandra', 'Bukkasagara', 'Shankanipura'], 'chennai': ['Kamaraj Nagar', 'Thirumudivakkam', 'Kanathur Reddikuppam', 'Chinna Nolambur', 'Anakaputhur', 'Madhanandapuram', 'Thiruneermalai', 'Pammal', 'Selaiyur', 'Pallikaranai', 'Adyar', 'Korattur', 'Madipakkam', 'Adambakkam', 'Keelkattalai', 'Kilpauk', 'Ambattur Industrial Estate', 'Ambattur', 'Chromepet', 'Tambaram', 'Manapakkam', 'Navalur', 'Pallavaram', 'Kolathur', 'Bangaruganapalli', 'Retteri Lake', 'Palavaram', 'Vadakkupattu', 'Siruseri', 'Pudupakkam', 'Jeth Nagar', 'Kotturpuram', 'Oragadam', 'Vengambakkam', 'Maraimalai Nagar', 'Kundrathur', 'Perumanttunallur', 'Peerakankaranai', 'Gerugambakkam', 'Nanmangalam', 'Thiruverkkadu', 'Kelambakkam', 'Thirumazhisai', 'Kovilambakkam', 'Gopalapuram', 'Kolapakkam - Vandalur', 'Mahindra World City', 'Vellakkal', 'Medavakkam', 'Ayanavaram', 'Ayappakkam', 'Moulivakkam', 'Tiruvottiyur', 'Perungudi', 'Perumbakkam', 'Padur', 'Poonamallee', 'Vengaivasal', 'Thoraipakkam', 'Perungalathur', 'Tambaram East', 'Guindy', 'Velachery', 'Urapakkam', 'Guduvancheri', 'Ramapuram', 'Royapettah', 'Perambur', 'KK Nagar', 'Raja Annamalai Puram', 'Chettipunyam', 'Paranur', 'Ullagaram', 'Pozhichalur', 'Kattupakkam', 'Sembakkam', 'Egattur', 'Padappai', 'Chembarambakkam', 'Mudichur', 'Velappanchavadi', 'Thiruvanmiyur', 'Valasaravakkam', 'Alwarpet', 'Sithalapakkam', 'Anna Nagar', 'Chitlapakkam', 'Semmancheri', 'Chetpet', 'Teynampet', 'Sholinganallur', 'Nanganallur', 'CIT Nagar', 'Mylapore', 'Irandankattalai', 'Iyyappanthangal', 'Lakshmipuram', 'Vinayakapuram', 'Mogappair', 'Kalipathur', 'Porur', 'Chengalpattu', 'Nungambakkam', 'Kolapakkam', 'Neelankarai', 'S.Kolathur-Kanchipuram', 'Banu Nagar', 'Oragadam Sriperambattur', 'Bhaskar Colony', 'Abiramapuram', 'Amanambakkam', 'Ekkatuthangal', 'T Nagar', 'Ottiambakkam', 'Kottivakkam', 'Vanagaram', 'Kodambakkam', 'Mannivakkam', 'Shenoy Nagar', 'Mahabalipuram', 'Choolaimedu', 'Avadi', 'Besant Nagar', 'Surappattu', 'Karapakkam', 'Bakthavatchalapuram', 'Maduravoyal', 'Vandalur', 'Injambakkam', 'Manimangalam', 'Moolakazhani', 'West Tambaram', 'Rathinamangalam', 'Kanathur', 'Kil Ayanambakkam', 'Vadapalani', 'Chitalapakkam', 'Irumbuli', 'Meenambakkam', 'kanchipuram', 'Rajakilpakkam', 'Zamin Pallavaram', 'Adhanur', 'Egmore', 'Padi', 'Karthikeyapuram', 'Mugalivakkam', 'Koyambedu', 'Saligramam', 'Madambakkam', 'Kulattur', 'Nandanam', 'Purasawalkam', 'Villivakkam', 'Mambakkam', 'Tambaram Sanatorium', 'Ashok Nagar', 'Virugambakkam', 'Thirumullaivoyal', 'Senneer Kuppam', 'Madhavaram', 'Choolai', 'Anna Nagar West', 'Mogappair East', 'West Mambalam', 'Thirutheri R.F.', 'Triplicane', 'Thousand Lights', 'Thandalam', 'Thazhambur', 'Kumananchavadi', 'Kovur', 'Puzhal', 'Thiruvallur', 'Periyamet', 'Thadaperumbakkam', 'Mappedu', 'Singaperumal Koil', 'Aminjikarai', 'Cholambedu', 'Ponniammanmedu', 'Vyasarpadi', 'Saidapet', 'Arumbakkam', 'Pulianthope', 'Kazhipattur', 'Mangadu', 'Anna Nagar West Extension', 'Uthandi', 'Tharapakkam', 'Mandaveli', 'Ottiyambakkam', 'Washermanpet', 'Varadharajapuram', 'Annanagar East', 'Ayapakkam', 'Surapet', 'Jamalia', 'Muttukadu', 'Okkiyampet', 'Pazhavanthangal', 'Tondiarpet', 'Agaramthen', 'Perumalpattu', 'Veppampattu', 'Thirunindravur', 'Pattabiram', 'Urapakkam West', 'Sevvapet', 'Vettuvankani', 'Nemilicheri', 'Nathamedu', 'Mannivakkam Extension', 'Natthamedu', 'Ponmar', 'Appur R.F.', 'Kayarambedu', 'Kamachi Nagar', 'Somanathapuram', 'Madhavaram Milk Colony', 'Nemmeli', 'Kannivakkam', 'Manali New Town', 'Nellitopa', 'Nandivaram-Guduvancheri', 'Nemilicherry', 'Walajabad', 'Thaiyur', 'Kovalam', 'Periyar Nagar', 'Sirukadal', 'Panneervakkam', 'Sree Mahaveer Nagar', 'Karayanchavadi', 'Red Hills', 'Manali', 'Katrambakkam', 'Mettukuppam', 'Kakkalur Industrial Estate', 'Sriperumbudur', 'Kalivandhapattu', 'Kadambur', 'Kodungaiyur East', 'Vetrivel Nagar', 'Kalavakkam', 'Maduravayal', 'Deenadayalan Nagar', 'Palavedu Pettai', 'Tiruvallur', 'Kachipuram Town', 'Soranjeri', 'Morai', 'Parivakkam', 'Sirukalathur', 'Thiruporur', 'Vadanemmeli', 'Dhanduma Nagar', 'Kolappancheri', 'Venkatamangalam', 'New Vellanur', 'Uthiramerur', 'Potheri', 'Kodungaiyur West', 'Thiruvidandhai', 'Nadukuthagai', 'Vallalar Nagar', 'Mangavaram', 'Kattankulathur', 'Nedunkundram', 'Old Washermanpet', 'Kilakondaiyur', 'Pandiyambakkam', 'Kanchipuram', 'Karanai Puthuchery', 'Salamangalam', 'Nandiambakkam', 'Kalpakkam', 'Edayanchavadi', 'Vandalur R.F.', 'Dharkast', 'Oragadam Ambattur', 'George Town', 'Moovarasampettai', 'Kilambakkam', 'Tirupandiyur', 'J Nagar', 'Mannur', 'Irungattukottai', 'Valarpuram', 'Ammapettai', 'Ankaputhur', 'Madurantakam', 'Minjur', 'Iyyapa Nagar', 'Perungavoor', 'Kuthambakkam', 'Illalur', 'Gummudipoondi', 'Naduveerapattu', 'Orathur', 'Eaichur', 'KAnchipuram', 'Ennore', 'Vengapakkam', 'Koovathur'], 'delhi': ['Sector 7 Dwarka', 'New Delhi', 'Sector 5 Dwarka', 'Sector 11 Dwarka', 'Sector 22 Dwarka', 'Burari', 'Sector 4 Dwarka', 'Sector 2 Dwarka', 'Sector 18 Dwarka', 'Sector 10 Dwarka', 'Sector 12 Dwarka', 'Sector 14 Dwarka', 'Sector 9 Dwarka', 'Rajpur', 'KG-III', 'Sector 6 Dwarka', 'Uday Park', 'Maidan Garhi', 'Uttam Nagar', 'Neb Sarai', 'Razapur Khurd', 'Karampura', 'Hastsal', 'Nawada', 'Chhattarpur', 'Sector 9 Rohini', 'Pitampura', 'Sector 24 Rohini', 'Bharthal', 'Paschim Vihar', 'Freedom Fighters Enclave', 'Subzi Mandi', 'Vikaspuri', 'Dwarka Mor', 'Chandra Park', 'Satbari', 'Sector 17 Dwarka', 'Okhla Industrial Area', 'Suraj Vihar', 'Vasant Kunj', 'Mittal Garden', 'Said-Ul-Ajaib', 'Chandan Hola', 'DLF Farms', 'Sector 13 Rohini', 'Sector 14 Rohini', 'Sewak Park', 'Hauz Khas', 'Karol Bagh', 'Gujranwala Town', 'Saket', 'Sheikh Sarai', 'Mahavir Enclave', 'Shivalik', 'Mukundpur', 'Mandi', 'Dhul Siras', 'Khanpur', 'Deenpur', 'Sector 18 Rohini', 'Jasola', 'Sangam Vihar', 'Mehrauli', 'Naraina', 'Sector 19 Rohini', 'Najafgarh Road Industrial Area', 'Najafgarh', 'Janakpuri', 'Sector 19 Dwarka', 'Munirka', 'Madhu Vihar', 'Sarita Vihar', 'Ashok Vihar', 'Greater Kailash II', 'Sector 16 Dwarka', 'Anand Vihar', 'Gwal Pahari', 'Timarpur', 'Vasant Vihar', 'Sector 3 Rohini', 'Rajpur Khurd Village', 'Sukhdev Vihar', 'Rajouri Garden', 'Kalkaji', 'Sector 4 Rohini', 'Mukherjee Nagar', 'Surajmal Vihar', 'Palam', 'Siddhartha Extension', 'Sector 23 Dwarka', 'Kotla Mubarakpur', 'Hari Nagar', 'Sarvodaya Enclave', 'Rajpur Khurd Extension', 'Sultanpur', 'Mayur Vihar Phase 1', 'Patparganj', 'Kalkaji Extension', 'Alaknanda', 'Patel Nagar', 'Chittaranjan Park', 'Gazipur', 'Jamia Nagar', 'Dilshad Garden', 'New Ashok Nagar', 'Safdarjung Enclave', 'Rajinder Nagar', 'Matiala', 'Sector 27 Dwarka', 'Sector 37 Rohini', 'Kalyan Vihar', 'Sector 3 Dwarka', 'Sant Nagar', 'Sector 1 Dwarka', 'Sector 15 Dwarka', 'Aya Nagar', 'Sector 23 Rohini', 'Bindapur', 'Sector 16B Dwarka', 'Sector 8 Dwarka', 'Panchsheel Park', 'Sector 22 Rohini', 'Vasundhara Enclave', 'Vinod Nagar West', 'Paharganj', 'Sector 16A Dwarka', 'Nangli Sakrawati', 'Sri Niwaspuri', 'Kishangarh', 'Sector 5 Rohini', 'Ramesh Nagar', 'Dera Mandi', 'Sector 8 Rohini', 'Sector 15 Rohini', 'Sector 29 Rohini', 'Greater Kailash I', 'Model Town', 'West End', 'Garhi', 'Punjabi Bagh', 'GTB Nagar', 'Malviya Nagar', 'Greater Kailash', 'South Extension II', 'Green Park Extension', 'New Friends Colony', 'Soami Nagar', 'Shahdara', 'Kailash Colony', 'Kondli', 'Narela', 'East Of Kailash', 'Civil Lines', 'Laxmi Nagar', 'Subhash Nagar', 'Shanti Niketan', 'Green Park', 'Defence Colony', 'Nizamuddin East', 'New Rajinder Nagar', 'Sector 25 Rohini', 'Anand Lok', 'Lajpat Nagar', 'Fateh Nagar', 'Rajokri', 'Bharat Vihar', 'Rani Khera', 'Nasirpur', 'Maharani Bagh', 'Bijwasan', 'Mithapur', 'Preet Vihar', 'Pul Prahlad Pur', 'Badarpur', 'R.K. Puram', 'Sagar Pur', 'Connaught Place', 'Jaitpur', 'Kirari Suleman Nagar', 'Nangloi', 'Anand Niketan', 'Sundar Nagar', 'Khirki Extension', 'Dashrath Puri', 'Azadpur', 'Panchsheel Enclave', 'Vivek Vihar', 'Sector 6 Rohini', 'Vishnu Garden', 'Sector 11 Rohini', 'Sector 16 Rohini', 'Sector 21 Rohini', 'Ranhola Extesion', 'Barwala', 'Johripur', 'Sultanpuri', 'Trilokpuri', 'Bankner', 'Krishna Nagar', 'Mandoli', 'Sudarshan Park', 'Gokalpur', 'South Extension I', 'Sector 38 Rohini', 'Dichaon Kalan', 'Baprola', 'Mayur Vihar Phase 3', 'Mangolpuri', 'Ghevra', 'Sector 31 Rohini', 'Shakti Nagar', 'Behta Hazipur', 'Sainik Farm', 'Moti Nagar', 'Sector 28 Dwarka', 'Ashok Nagar', 'Ranhola', 'Pandav Nagar', 'Karawal Nagar', 'Tajpur Pahari Village', 'Sector 39 Rohini', 'Budh Vihar', 'Tri Nagar', 'Safdarjung Development Area', 'New Mustafabad', 'Mahipalpur', 'Bhalswa', 'Shakarpur Khas', 'Nilothi', 'Tilak Nagar', 'West Sagarpur', 'Mohan Cooperative Industrial Estate', 'Khaira', 'Sector 7 Rohini', 'Vijay Nagar', 'Raju Parak Extension', 'Bali Nagar', 'Sadar Bazaar', 'Yamuna Vihar', 'Roop Nagar', 'Sector 26 Rohini', 'Bhatti Kalan', 'Rohini Sector 28', 'Shastri Nagar', 'Sector 20 Rohini', 'Rohini Extension', 'Sector 7G', 'Sector 17 Rohini', 'Malka Ganj', 'Tagore Garden Extension', 'Kirti Nagar', 'Sarvapriya Vihar', 'Pochanpur Colony', 'Dabri', 'Sector 23B Dwarka', 'Jharoda Majra Burari', 'Swasthya Vihar', 'Raja Garden', 'Inder Puri', 'Asola', 'Mukherji Park', 'Shalimar Bagh', 'Sector 67', 'Govindpuri', 'Mansarover Garden', 'Arjun Nagar', 'Navjeevan Vihar', 'Palam Extension', 'Shakur Basti', 'Jangpura', 'Ganesh Nagar', 'Shakurpur', 'Mandawali', 'Kadarpur', 'Geetanjali Enclave', 'Sarai Rohilla', 'Rangpuri'], 'gurgaon': ['Sector 69', 'Sector 89', 'Sector 76', 'Sector 85', 'Sector 111', 'Sector 80', 'Sector 70A', 'Sector 47', 'Sector 84', 'Manesar', 'Sector 49', 'Nurpur Jharsa', 'Sector 65', 'Sector 36A', 'Sector 82A', 'Sector 89A', 'Sector 88A', 'Sector 107', 'Sector 99', 'Sector 92', 'Sector 102', 'Sector 79', 'Sector 63', 'Sector 108', 'Sector 37C', 'Sohna', 'Sector 77', 'Sector 106', 'Se

In [4]:
result = (
    df.groupby('city')['locality']
    .unique()
    .reset_index()
)

print(result)

        city                                           locality
0  ahmedabad  [Shela, Bopal, Ghuma, Jagatpur, Chandlodia, Vi...
1  bengaluru  [Balagere, Chokkanahalli, Gunjur Palya, Kambip...
2    chennai  [Kamaraj Nagar, Thirumudivakkam, Kanathur Redd...
3      delhi  [Sector 7 Dwarka, New Delhi, Sector 5 Dwarka, ...
4    gurgaon  [Sector 69, Sector 89, Sector 76, Sector 85, S...
5  hyderabad  [Begumpet, Kondapur, Neknampur, Sangareddy, Kp...
6    kolkata  [Mastarpara, South 24 Parganas, Belghoria, Shy...
7     mumbai  [Makane Kapase, Vile Parle East, Mira Bhayanda...
8       pune  [Wadgaon Sheri, Punawale, Kalyani Nagar, Ravet...

In [8]:
ahmedabad_areas = sorted(df[df['city'] == 'ahmedabad']['locality'].dropna().unique())
bengaluru_areas = sorted(df[df['city'] == 'bengaluru']['locality'].dropna().unique())
chennai_areas = sorted(df[df['city'] == 'chennai']['locality'].dropna().unique())
delhi_areas = sorted(df[df['city'] == 'delhi']['locality'].dropna().unique())
mumbai_areas = sorted(df[df['city'] == 'mumbai']['locality'].dropna().unique())
gurgaon_areas = sorted(df[df['city'] == 'gurgaon']['locality'].dropna().unique())
hyderabad_areas = sorted(df[df['city'] == 'hyderabad']['locality'].dropna().unique())
kolkata_areas = sorted(df[df['city'] == 'kolkata']['locality'].dropna().unique())
pune_areas = sorted(df[df['city'] == 'pune']['locality'].dropna().unique())

In [9]:
print(len(ahmedabad_areas))
print(len(bengaluru_areas))
print(len(chennai_areas))
print(len(delhi_areas))
print(len(mumbai_areas))
print(len(gurgaon_areas))
print(len(hyderabad_areas))
print(len(kolkata_areas))
print(len(pune_areas))

154
490
305
277
118
152
260
260
180

In [10]:
areas_df = df[['city', 'locality']].dropna().drop_duplicates()

print(areas_df.shape)
areas_df.head()

(2196, 2)

        city    locality
0  ahmedabad       Shela
2  ahmedabad       Bopal
4  ahmedabad       Ghuma
5  ahmedabad    Jagatpur
6  ahmedabad  Chandlodia

In [16]:
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
import pandas as pd
import time


geolocator = Nominatim(user_agent="houseiq")


coordinates = []


for _, row in areas_df.iterrows():

    city = row['city']
    locality = row['locality']

    query = f"{locality}, {city}, India"

    try:

        location = geolocator.geocode(
            query,
            timeout=10
        )


        if location:

            coordinates.append({

                'city': city,

                'locality': locality,

                'latitude': location.latitude,

                'longitude': location.longitude

            })

            print(f"✓ {query}")


        else:

            coordinates.append({

                'city': city,

                'locality': locality,

                'latitude': None,

                'longitude': None

            })

            print(f"✗ {query}")


        time.sleep(1)


    except GeocoderTimedOut:


        coordinates.append({

            'city': city,

            'locality': locality,

            'latitude': None,

            'longitude': None

        })

        print(f"Timeout : {query}")



coords_df = pd.DataFrame(coordinates)

coords_df.to_csv(

    "data/coordinates.csv",

    index=False

)

print("Saved Successfully")

✓ Shela, ahmedabad, India
✓ Bopal, ahmedabad, India
✓ Ghuma, ahmedabad, India
✓ Jagatpur, ahmedabad, India
✓ Chandlodia, ahmedabad, India
✓ Vishala, ahmedabad, India
✓ Gota, ahmedabad, India
✓ Vaishno Devi Circle, ahmedabad, India
✓ Shantigram, ahmedabad, India
✓ Bodakdev, ahmedabad, India
✓ Vasna, ahmedabad, India
✗ Iscon Ambli Road, ahmedabad, India
✓ Chandkheda, ahmedabad, India
✓ South Bopal, ahmedabad, India
✗ Zundal, ahmedabad, India
✓ Jodhpur, ahmedabad, India
✓ Prahlad Nagar, ahmedabad, India
✓ Nirnay Nagar, ahmedabad, India
✓ Paldi, ahmedabad, India
✓ Science City, ahmedabad, India
✓ Ambawadi, ahmedabad, India
✓ Satellite, ahmedabad, India
✓ Sola, ahmedabad, India
✓ Shilaj, ahmedabad, India
✓ Tragad, ahmedabad, India
✓ Ramdev Nagar, ahmedabad, India
✓ Thaltej, ahmedabad, India
✓ Naranpura, ahmedabad, India
✓ Chharodi, ahmedabad, India
✓ Makarba, ahmedabad, India
✓ Vastrapur, ahmedabad, India
✓ Motera, ahmedabad, India
✓ Shyamal, ahmedabad, India
✓ Ognaj, ahmedabad, India
✓ Maninagar, ahmedabad, India
✓ Ghatlodiya, ahmedabad, India
✓ Science Park, ahmedabad, India
✓ Ellisbridge, ahmedabad, India
✗ University Area, ahmedabad, India
✓ Bhat, ahmedabad, India
✓ Memnagar, ahmedabad, India
✓ Vastral, ahmedabad, India
✗ Bilasiya, ahmedabad, India
✓ Ambli, ahmedabad, India
✓ Vikram Nagar, ahmedabad, India
✓ Hanspura, ahmedabad, India
✓ Shantipura, ahmedabad, India
✗ Nana Chiloda, ahmedabad, India
✗ Narolgam, ahmedabad, India
✓ GIDC Naroda, ahmedabad, India
✓ New Ranip, ahmedabad, India
✓ Odhav, ahmedabad, India
✓ Bhadaj, ahmedabad, India
✓ Navrangpura, ahmedabad, India
✓ Vejalpur, ahmedabad, India
✓ Isanpur, ahmedabad, India
✓ Shahibaug, ahmedabad, India
✓ Sarkhej, ahmedabad, India
✓ Chanakyapuri, ahmedabad, India
✓ Nava Naroda, ahmedabad, India
✓ Hansol, ahmedabad, India
✓ Navarangpura, ahmedabad, India
✓ New Maninagar, ahmedabad, India
✓ Sanand, ahmedabad, India
✓ Gurukul, ahmedabad, India
✓ Lambha, ahmedabad, India
✓ Koteshwar, ahmedabad, India
✓ Nikol, ahmedabad, India
✗ Vinzol, ahmedabad, India
✓ Naroda, ahmedabad, India
✓ Bavla, ahmedabad, India
✓ Vatva, ahmedabad, India
✗ Ujala Circle, ahmedabad, India
✓ Ranip, ahmedabad, India
✓ Changodar, ahmedabad, India
✓ Gulbai Tekra, ahmedabad, India
✓ Juhapura, ahmedabad, India
✓ Usmanpura, ahmedabad, India
✓ Dholera, ahmedabad, India
✓ Daskroi, ahmedabad, India
✓ Mahadev Nagar, ahmedabad, India
✗ Old Wadaj, ahmedabad, India
✓ Thakkarbapa Nagar, ahmedabad, India
✓ Sanathal, ahmedabad, India
✓ Ghodasar, ahmedabad, India
✓ Khokhra, ahmedabad, India
✓ Godhavi, ahmedabad, India
✗ Noble Nagar Tenament, ahmedabad, India
✓ Nava Vadaj, ahmedabad, India
✓ Ramol, ahmedabad, India
✓ Sabarmati, ahmedabad, India
✗ Jodhpur Tekra, ahmedabad, India
✓ Hathijan, ahmedabad, India
✓ Acher, ahmedabad, India
✗ Khoraj, ahmedabad, India
✓ Sanidhya, ahmedabad, India
✗ Jivrajpark, ahmedabad, India
✓ Kathwada, ahmedabad, India
✓ Amraiwadi, ahmedabad, India
✓ Manipur, ahmedabad, India
✗ Jasodanagr, ahmedabad, India
✓ Aslali, ahmedabad, India
✓ Moraiya, ahmedabad, India
✗ Enasan, ahmedabad, India
✗ Saraspur, ahmedabad, India
✗ Vinobanagar, ahmedabad, India
✓ Krishna Nagar Society, ahmedabad, India
✗ Jaldhara-3, ahmedabad, India
✗ Saijpur Bogha, ahmedabad, India
✓ Dholka, ahmedabad, India
✓ Bapunagar, ahmedabad, India
✗ Kotarpur, ahmedabad, India
✗ Raska, ahmedabad, India
✓ Kasindra, ahmedabad, India
✓ Hansalpur Becharaji, ahmedabad, India
✓ Kuber Nagar, ahmedabad, India
✓ Hatkeshwar, ahmedabad, India
✗ Bakrol Bujrang, ahmedabad, India
✗ Ayojan Nagar, ahmedabad, India
✗ Lilapur, ahmedabad, India
✓ Khadia, ahmedabad, India
✓ Kankaria, ahmedabad, India
✓ Hebatpur, ahmedabad, India
✗ Rambagh, ahmedabad, India
✗ Meghani Nagar, ahmedabad, India
✓ Janta Nagar, ahmedabad, India
✓ Gokuldham, ahmedabad, India
✓ Kuha, ahmedabad, India
✗ Keshav Nagar, ahmedabad, India
✓ Navjivan, ahmedabad, India
✓ Dani Limda, ahmedabad, India
✓ India Colony, ahmedabad, India
✓ Geratpur, ahmedabad, India
✗ GIDC Vatwa, ahmedabad, India
✓ Shahpur, ahmedabad, India
✓ Asarwa, ahmedabad, India
✗ Dudeshwar, ahmedabad, India
✓ Behrampura, ahmedabad, India
✓ Kalupur, ahmedabad, India
✓ Sardar Colony, ahmedabad, India
✓ Bhadra, ahmedabad, India
✓ Khanpur, ahmedabad, India
✗ Pipan, ahmedabad, India
✗ Devdholera, ahmedabad, India
✓ Daran, ahmedabad, India
✓ Gamdi, ahmedabad, India
✓ Lapkaman, ahmedabad, India
✗ Vasna Iyava, ahmedabad, India
✓ Gandhinagar, ahmedabad, India
✓ Telav, ahmedabad, India
✓ Chekhla, ahmedabad, India
✗ Chhabasar, ahmedabad, India
✓ Kolat, ahmedabad, India
✓ Rakhial, ahmedabad, India
✓ Balagere, bengaluru, India
✓ Chokkanahalli, bengaluru, India
✓ Gunjur Palya, bengaluru, India
✓ Kambipura, bengaluru, India
✓ Chikkakannalli, bengaluru, India
✓ V. Kallahalli, bengaluru, India
✓ Electronic City, bengaluru, India
✓ Yadavanahalli, bengaluru, India
✓ Gummanahalli, bengaluru, India
✓ Kadagrahara, bengaluru, India
✓ Anantapura, bengaluru, India
✓ Dommasandra, bengaluru, India
✓ Electronic City Phase 2, bengaluru, India
✓ Chikkanagamangala, bengaluru, India
✓ Devinagar, bengaluru, India
✗ Kumbalgodu, bengaluru, India
✓ Kalkere, bengaluru, India
✓ Varthur, bengaluru, India
✓ Kaggadasapura, bengaluru, India
✗ Bedarahalli, bengaluru, India
✓ Thanisandra, bengaluru, India
✗ Boodihal, bengaluru, India
✓ Murugeshpalya, bengaluru, India
✓ Richards Town, bengaluru, India
✓ K R Puram, bengaluru, India
✓ Vasanth Nagar, bengaluru, India
✓ Hosahalli, bengaluru, India
✓ Byatarayanapura, bengaluru, India
✓ Halasahalli, bengaluru, India
✓ Doddakannelli, bengaluru, India
✓ Kadugodi, bengaluru, India
✗ Uttarahalli -Manavarthekaval, bengaluru, India
✓ Begur, bengaluru, India
✗ Bhoganhalli, bengaluru, India
✓ Byrathi, bengaluru, India
✓ Chikkagubbi Village, bengaluru, India
✓ Vakil Garden City, bengaluru, India
✓ Rayasandra, bengaluru, India
✓ Kannamangala - Whitefield Hoskote Road, bengaluru, India
✓ Sarjapur, bengaluru, India
✓ Bellandur, bengaluru, India
✓ Kalyan Nagar, bengaluru, India
✓ New Tippasandra, bengaluru, India
✓ Kumaraswamy Layout, bengaluru, India
✓ Cox Town, bengaluru, India
✓ Narayanapura, bengaluru, India
✓ Varanasi, bengaluru, India
✓ Budigere Cross, bengaluru, India
✓ RR Nagar, bengaluru, India
✓ Hoodi, bengaluru, India
✓ Visthar, bengaluru, India
✗ Thurahalli, bengaluru, India
✓ Rajajinagar, bengaluru, India
✓ Panathur, bengaluru, India
✓ Kasavanahalli, bengaluru, India
✓ Medahalli, bengaluru, India
✓ C V Raman Nagar, bengaluru, India
✗ Lingadheeranahalli, bengaluru, India
✓ HSR Layout, bengaluru, India
✓ Koramangala, bengaluru, India
✓ Kasturi Nagar, bengaluru, India
✓ Sheshadripuram, bengaluru, India
✓ Horamavu, bengaluru, India
✓ Hebbal Kempapura, bengaluru, India
✓ Bilekahalli, bengaluru, India
✓ NRI Layout, bengaluru, India
✓ Shivaji Nagar, bengaluru, India
✓ Agrahara Layout, bengaluru, India
✗ Rustam Bagh Layout, bengaluru, India
✓ Mallasandra, bengaluru, India
✓ Arakere, bengaluru, India
✗ Talaghattapura, bengaluru, India
✓ Subramanyapura, bengaluru, India
✓ Gunjur Village, bengaluru, India
✗ Munnekollal, bengaluru, India
✓ Yelahanka New Town, bengaluru, India
✓ Vajarahalli, bengaluru, India
✓ Basavanagudi, bengaluru, India
✓ Mahadevapura, bengaluru, India
✓ Hulimavu, bengaluru, India
✗ Jyotipuram, bengaluru, India
✓ Mahalakshmi Layout, bengaluru, India
✓ Padmanabhanagar, bengaluru, India
✓ Gottigere, bengaluru, India
✓ S.G. Palya, bengaluru, India
✓ Cooke Town, bengaluru, India
✓ Kodathi, bengaluru, India
✓ JP Nagar, bengaluru, India
✓ Whitefield, bengaluru, India
✓ Puttenahalli, bengaluru, India
✓ Indira Nagar, bengaluru, India
✓ Banaswadi, bengaluru, India
✓ Nagarbhavi, bengaluru, India
✓ Cheemasandra, bengaluru, India
✓ Banashankari Temple Ward, bengaluru, India
✓ Yeswanthpur, bengaluru, India
✓ Dooravani Nagar, bengaluru, India
✓ Basavanagar, bengaluru, India
✓ Frazer Town, bengaluru, India
✓ Hosakerehalli, bengaluru, India
✗ Jnana Ganga Nagar, bengaluru, India
✓ Yelahanka, bengaluru, India
✓ RMV Extension Stage 2, bengaluru, India
✓ Bommanahalli, bengaluru, India
✓ Kannuru, bengaluru, India
✓ Akshayanagar, bengaluru, India
✓ HBR Layout, bengaluru, India
✓ Kengeri, bengaluru, India
✓ Kodagalahatti, bengaluru, India
✗ Huvinane, bengaluru, India
✗ Kadugodi Plantation, bengaluru, India
✓ Nagareshwara - Nagenahalli, bengaluru, India
✓ Benson Town, bengaluru, India
✗ Kodipur, bengaluru, India
✗ Armane Nagar, bengaluru, India
✗ Essel Gardens, bengaluru, India
✗ Ramanashree California Gardens Layout, bengaluru, India
✓ Richmond Town, bengaluru, India
✓ Kanakapura, bengaluru, India
✓ Amrutahalli, bengaluru, India
✓ Singasandra, bengaluru, India
✓ Jakkur, bengaluru, India
✓ Kogilu, bengaluru, India
✓ Nagavara, bengaluru, India
✓ Bommenahalli, bengaluru, India
✓ Virupakshapura, bengaluru, India
✓ Doddanekundi, bengaluru, India
✗ Bikasipura, bengaluru, India
✓ GB Palya, bengaluru, India
✗ Hallehalli, bengaluru, India
✓ Doddakallasandra, bengaluru, India
✓ Sultanpalya, bengaluru, India
✓ K Channasandra, bengaluru, India
✗ Tirumanahalli, bengaluru, India
✓ Sompura, bengaluru, India
✓ Anchepalya, bengaluru, India
✓ Sahakara Nagar, bengaluru, India
✓ Vijayanagar, bengaluru, India
✗ Jagajeevanram Nagar, bengaluru, India
✓ Battarahalli, bengaluru, India
✓ Halasuru, bengaluru, India
✓ Hosur, bengaluru, India
✓ Nehru Nagar, bengaluru, India
✓ Anekal, bengaluru, India
✓ Kempegowda Nagar, bengaluru, India
✓ Parappana Agrahara, bengaluru, India
✓ Jalahalli, bengaluru, India
✓ Sanjaynagar, bengaluru, India
✗ R.K. Hegde Nagar, bengaluru, India
✓ Kadubeesanahalli, bengaluru, India
✓ Brookefield, bengaluru, India
✓ Ramamurthy Nagar, bengaluru, India
✓ Thirumagondanahalli, bengaluru, India
✓ Kammanahalli, bengaluru, India
✓ Hongasandra, bengaluru, India
✓ Hebbal, bengaluru, India
✗ Jeevan Bima Nagar, bengaluru, India
✓ Vidyaranyapura, bengaluru, India
✗ Chandrasekarapura, bengaluru, India
✓ Kyalasanahalli, bengaluru, India
✓ Harlur, bengaluru, India
✓ Choodasandra, bengaluru, India
✓ Marathahalli, bengaluru, India
✓ Chandapura, bengaluru, India
✓ Kudlu Gate, bengaluru, India
✓ BTM Layout, bengaluru, India
✓ Bommasandra, bengaluru, India
✓ Kudlu, bengaluru, India
✓ Kothanur, bengaluru, India
✓ Malleswaram, bengaluru, India
✓ Jayanagar, bengaluru, India
✓ Nagondanahalli, bengaluru, India
✓ New Baiyyappanahalli, bengaluru, India
✓ Sanjeevini Nagar, bengaluru, India
✗ Reliaable Tranquil Layout, bengaluru, India
✓ Thirupalya, bengaluru, India
✓ Goravigere, bengaluru, India
✗ Binnipete, bengaluru, India
✓ Devarachikkana Halli, bengaluru, India
✓ Yelachenahalli, bengaluru, India
✓ Konanakunte, bengaluru, India
✓ Doddabommasandra, bengaluru, India
✓ Annapurneshwari Nagar, bengaluru, India
✓ Kalena Agrahara, bengaluru, India
✓ Carmelaram, bengaluru, India
✓ Hoskote, bengaluru, India
✓ Kaggalipura, bengaluru, India
✓ Devanahalli, bengaluru, India
✓ Attibele, bengaluru, India
✓ T Dasarahalli, bengaluru, India
✓ Shanti Nagar, bengaluru, India
✓ Bidaraguppe, bengaluru, India
✓ Chansandra, bengaluru, India
✗ Chikkabana Halli, bengaluru, India
✓ Bengaluru North, bengaluru, India
✓ Sampangi Rama Nagar, bengaluru, India
✗ Chikkasanne, bengaluru, India
✓ Singapura, bengaluru, India
✗ Thirumalashettyhally, bengaluru, India
✓ Hennur, bengaluru, India
✓ Kodipalya, bengaluru, India
✓ Thindlu, bengaluru, India
✓ Madhura Nagar, bengaluru, India
✓ Chikkadunnasandra, bengaluru, India
✓ Samethanahalli, bengaluru, India
✓ Gattahalli, bengaluru, India
✓ KPC Layout, bengaluru, India
✗ Katamnallur, bengaluru, India
✓ Sampigehalli, bengaluru, India
✗ Bidare Agraha, bengaluru, India
✓ Konadasapura, bengaluru, India
✓ Muneshwara Nagar, bengaluru, India
✗ Sannatammanahalli, bengaluru, India
✓ Basapura, bengaluru, India
✓ Baiyappanahalli, bengaluru, India
✗ BEML Cooperative Society Layout, bengaluru, India
✓ Bendiganahalli, bengaluru, India
✓ Chambenahalli, bengaluru, India
✓ Yamare, bengaluru, India
✓ Huvinayakanahalli, bengaluru, India
✓ B.Hosahalli, bengaluru, India
✓ Mangammanapalya, bengaluru, India
✗ Boovanahalli, bengaluru, India
✓ Victoria Layout, bengaluru, India
✓ Hunasamaranahalli, bengaluru, India
✗ Navarathna Agrahara, bengaluru, India
✗ Kolur, bengaluru, India
✓ Gunjur, bengaluru, India
✓ Raghuvanahalli, bengaluru, India
✓ Jigani, bengaluru, India
✗ Thattanahalli, bengaluru, India
✗ Suradhenupura, bengaluru, India
✓ Chikkabanavara, bengaluru, India
✓ Vittasandra, bengaluru, India
✓ Kartik Nagar, bengaluru, India
✓ Kachamaranahalli, bengaluru, India
✓ Kaikondrahalli, bengaluru, India
✓ Kodigehalli, bengaluru, India
✓ Nagegowdanapalya, bengaluru, India
✓ Vignana Kendra, bengaluru, India
✗ Kaval Bairasandra, bengaluru, India
✗ Srinivaspura, bengaluru, India
✓ Banashankari, bengaluru, India
✗ Thyvakanahally, bengaluru, India
✓ Chamrajpet, bengaluru, India
✗ Aavalahalli, bengaluru, India
✓ Chikkalasandra, bengaluru, India
✓ Tejaswini Nagar, bengaluru, India
✓ Hemmigepura, bengaluru, India
✓ Somasundarapalya, bengaluru, India
✗ Kuthaganahalli, bengaluru, India
✓ Margondanahalli, bengaluru, India
✗ Kariyana Palya, bengaluru, India
✓ Marsur, bengaluru, India
✓ Abbigere, bengaluru, India
✓ Harohalli, bengaluru, India
✓ Kengeri Satellite Town, bengaluru, India
✓ Junnasandra, bengaluru, India
✓ Chandra Layout Stage 1, bengaluru, India
✗ Volagerekallahalli, bengaluru, India
✓ Gonighattapura, bengaluru, India
✓ Adugodi, bengaluru, India
✓ Jayamahal, bengaluru, India
✓ Sivanchetti Gardens, bengaluru, India
✓ ISRO Layout, bengaluru, India
✗ Mullur, bengaluru, India
✓ BTM Layout 2nd Stage, bengaluru, India
✓ Jalahalli West, bengaluru, India
✗ Bangalore City Municipal Corporation Layout, bengaluru, India
✓ Domlur Layout, bengaluru, India
✗ Kithaganur Village, bengaluru, India
✓ Yadiyuru, bengaluru, India
✓ Geddalahalli, bengaluru, India
✗ Uttarahalli Hobli, bengaluru, India
✓ Huskur, bengaluru, India
✓ Kadugodi Industrial Area, bengaluru, India
✗ Channanayakanapalya, bengaluru, India
✓ Madivala, bengaluru, India
✓ Mavalli, bengaluru, India
✓ Mathikere, bengaluru, India
✗ Doddagattiganabbe, bengaluru, India
✗ Devara Jeevanahalli, bengaluru, India
✓ RT Nagar, bengaluru, India
✓ Ganganagar, bengaluru, India
✗ Byagadadhenahalli, bengaluru, India
✓ Ullalu, bengaluru, India
✗ Kasuvanahalli, bengaluru, India
✓ Chikkadasarahalli, bengaluru, India
✓ Sunkalpalya, bengaluru, India
✓ Lakshmisagara, bengaluru, India
✓ Kacharakanahalli, bengaluru, India
✓ Kamakshipalya, bengaluru, India
✓ Prakruthi Township, bengaluru, India
✓ Mahalakshmipuram, bengaluru, India
✓ Gantiganahalli, bengaluru, India
✗ Bagalakunte, bengaluru, India
✓ Kodihalli, bengaluru, India
✗ Srirampuram, bengaluru, India
✓ Bileshivale, bengaluru, India
✗ Chandra Layout Extension, bengaluru, India
✓ Mailasandra, bengaluru, India
✓ Bagalur, bengaluru, India
✗ Naganaikanahalli, bengaluru, India
✓ Agrahara, bengaluru, India
✗ Bychapura, bengaluru, India
✗ Bennigana Halli, bengaluru, India
✗ Udayagiri, bengaluru, India
✓ Jigala, bengaluru, India
✓ Channahalli, bengaluru, India
✗ Chikkabellandur, bengaluru, India
✗ Chinnapanna Halli, bengaluru, India
✓ Dasanayakanahalli, bengaluru, India
✓ Sarvagnanagar, bengaluru, India
✗ Kithaganur Colony, bengaluru, India
✓ Gopasandra, bengaluru, India
✓ Mallathahalli, bengaluru, India
✓ Lingarajapuram, bengaluru, India
✗ Yelachanayakanapura, bengaluru, India
✓ Kattigenahalli, bengaluru, India
✓ Ramanagara, bengaluru, India
✓ Basaveshwara Nagar, bengaluru, India
✓ Sunkadakatte, bengaluru, India
✓ Ittangur, bengaluru, India
✗ Kothnur Narayanapura, bengaluru, India
✗ Bisnahalli, bengaluru, India
✓ Doddabele, bengaluru, India
✓ Dasanapura, bengaluru, India
✓ Anjanapura Township, bengaluru, India
✓ S.Medihalli, bengaluru, India
✓ Hullahalli, bengaluru, India
✓ Basavanapura, bengaluru, India
✓ Bharat Nagar, bengaluru, India
✓ Anjanapura, bengaluru, India
✓ Banashankari 6th Stage 4th Block, bengaluru, India
✓ SMV Layout, bengaluru, India
✓ Ashok Nagar, bengaluru, India
✗ Kempalingapura, bengaluru, India
✗ Doddabidrakallu, bengaluru, India
✗ Nagadevana Halli, bengaluru, India
✓ Andrahalli, bengaluru, India
✗ Vidyamanya Nagar, bengaluru, India
✓ Gnana Bharathi, bengaluru, India
✗ Ullal Uppanagar, bengaluru, India
✓ Vishveshwaraya Nagar, bengaluru, India
✓ Chikkabettahalli, bengaluru, India
✓ Attiguppe, bengaluru, India
✗ Thammenahalli Village, bengaluru, India
✓ Thathaguni, bengaluru, India
✗ Byadralli, bengaluru, India
✓ Gangondanahalli, bengaluru, India
✓ Judicial Layout, bengaluru, India
✓ Nelamangala, bengaluru, India
✓ Kadabagere, bengaluru, India
✓ Bendre Nagar, bengaluru, India
✗ Kithiganur, bengaluru, India
✗ Ckikkakammana Halli, bengaluru, India
✗ Hosahalli Gollarapalya, bengaluru, India
✗ Vaderamanchana Halli, bengaluru, India
✓ Tunganagara, bengaluru, India
✓ Hancharahalli Village, bengaluru, India
✓ Chikkagubbi, bengaluru, India
✓ Koppa Gate, bengaluru, India
✓ Manganahalli, bengaluru, India
✓ Kachohalli, bengaluru, India
✓ Pavamanapura, bengaluru, India
✓ ITI Layout, bengaluru, India
✓ Kurubarahalli, bengaluru, India
✗ Thotada Guddadhalli Village, bengaluru, India
✓ Maruthi Nagar, bengaluru, India
✓ Vimanapura, bengaluru, India
✓ Neraluru, bengaluru, India
✓ Bidarahalli, bengaluru, India
✓ Anagalapura, bengaluru, India
✓ Ejipura, bengaluru, India
✗ Syndicate Bank Employees Housing Society Layout, bengaluru, India
✓ Hebbagodi, bengaluru, India
✓ Varadanahalli, bengaluru, India
✓ Deepanjali Nagar, bengaluru, India
✓ Nadaprabhu Kempegowda layout, bengaluru, India
✓ Kada Agrahara, bengaluru, India
✓ Tigalarapalya, bengaluru, India
✓ Seegehalli, bengaluru, India
✓ Dodda Gubbi, bengaluru, India
✗ Rukmini Nagar, bengaluru, India
✗ Kariobanahalli, bengaluru, India
✓ Soundarya Layout, bengaluru, India
✗ Kammassandra, bengaluru, India
✓ D Group Employees Layout, bengaluru, India
✓ Yelahanka Satellite Town, bengaluru, India
✓ HAL, bengaluru, India
✓ Rajanukunte, bengaluru, India
✓ Kamala Nagar, bengaluru, India
✓ Sidedahalli, bengaluru, India
✓ Kammasandra, bengaluru, India
✓ Aduru, bengaluru, India
✓ Laggere, bengaluru, India
✓ Hirandahalli, bengaluru, India
✓ Machohalli, bengaluru, India
✓ Mylasandra, bengaluru, India
✗ Bhyraveshwara Nagar, bengaluru, India
✗ Halasahalli Thippasandra, bengaluru, India
✓ Rampura, bengaluru, India
✓ S.Bingipura, bengaluru, India
✓ Arasinakunte, bengaluru, India
✓ Ramasandra, bengaluru, India
✗ Kathirguppe, bengaluru, India
✗ Madanayakahalli, bengaluru, India
✓ Virupakshipura, bengaluru, India
✓ Wilson Garden, bengaluru, India
✓ Banashankari 6th Stage 6th Block, bengaluru, India
✗ Totadaguddadahalli, bengaluru, India
✓ Maruthi Sevanagar, bengaluru, India
✗ J C Nager, bengaluru, India
✓ Vibhutipura, bengaluru, India
✓ Panduranga Nagar, bengaluru, India
✓ Bapuji Nagar, bengaluru, India
✓ Mandur, bengaluru, India
✓ Peenya, bengaluru, India
✗ Thirumanahalli, bengaluru, India
✓ Guguttahalli, bengaluru, India
✓ Azad Nagar, bengaluru, India
✗ Mugalur, bengaluru, India
✓ Byalahalli, bengaluru, India
✗ Thathnur Plantation, bengaluru, India
✓ Magadi, bengaluru, India
✓ CK Palya, bengaluru, India
✓ Maragondanahalli, bengaluru, India
✓ Bodanahosahalli, bengaluru, India
✓ Nimbekaipura, bengaluru, India
✓ Doddanagamangala, bengaluru, India
✓ Hesaraghatta, bengaluru, India
✓ Harapanahalli, bengaluru, India
✓ Nandini Layout, bengaluru, India
✗ Dobbsapet, bengaluru, India
✓ Dombarahalli, bengaluru, India
✗ Doddadunnasandra, bengaluru, India
✓ Doddaballapura, bengaluru, India
✓ Veerasagara, bengaluru, India
✗ Kengeri Hobli, bengaluru, India
✓ Attibele Industrial Area, bengaluru, India
✗ Bhimenahalli, bengaluru, India
✓ Bheemanakuppe, bengaluru, India
✗ Chikballapur District, bengaluru, India
✗ Mitganahalli, bengaluru, India
✗ Varadharaja Nagar, bengaluru, India
✗ Ramnagara, bengaluru, India
✗ Sathnur, bengaluru, India
✓ Kadugondanahalli, bengaluru, India
✗ Srinivaspur, bengaluru, India
✓ Chikkabidarakallu, bengaluru, India
✓ Dasarahalli, bengaluru, India
✓ Singanayakanahalli, bengaluru, India
✓ Bannerughatta, bengaluru, India
✓ T.B Cross, bengaluru, India

In [19]:
cor = pd.read_csv("data/coordinates.csv")

In [20]:
missing = cor[cor['latitude'].isna()]

print(len(missing))

missing[['city','locality']].head(20)

508

          city              locality
11   ahmedabad      Iscon Ambli Road
14   ahmedabad                Zundal
38   ahmedabad       University Area
42   ahmedabad              Bilasiya
47   ahmedabad          Nana Chiloda
48   ahmedabad              Narolgam
68   ahmedabad                Vinzol
72   ahmedabad          Ujala Circle
81   ahmedabad             Old Wadaj
87   ahmedabad  Noble Nagar Tenament
91   ahmedabad         Jodhpur Tekra
94   ahmedabad                Khoraj
96   ahmedabad            Jivrajpark
100  ahmedabad            Jasodanagr
103  ahmedabad                Enasan
104  ahmedabad              Saraspur
105  ahmedabad           Vinobanagar
107  ahmedabad            Jaldhara-3
108  ahmedabad         Saijpur Bogha
111  ahmedabad              Kotarpur

In [21]:
missing[['city','locality']].to_csv(
    "data/missing_coordinates.csv",
    index=False
)

In [22]:
from geopy.geocoders import Nominatim
import time

geolocator = Nominatim(user_agent="houseiq")


for i, row in missing.iterrows():

    query = f"{row['locality']}, {row['city']}, India"

    try:

        location = geolocator.geocode(
            query,
            timeout=10
        )

        if location:

            df.loc[i, 'latitude'] = location.latitude
            df.loc[i, 'longitude'] = location.longitude

            print("✓", query)

        else:

            print("✗", query)

        time.sleep(1)

    except Exception as e:

        print(query, e)

✗ Iscon Ambli Road, ahmedabad, India
✗ Zundal, ahmedabad, India
✗ University Area, ahmedabad, India
✗ Bilasiya, ahmedabad, India
✗ Nana Chiloda, ahmedabad, India
✗ Narolgam, ahmedabad, India
✗ Vinzol, ahmedabad, India
✗ Ujala Circle, ahmedabad, India
✗ Old Wadaj, ahmedabad, India
✗ Noble Nagar Tenament, ahmedabad, India
✗ Jodhpur Tekra, ahmedabad, India
✗ Khoraj, ahmedabad, India

KeyboardInterrupt:

In [23]:
missing = cor[cor['latitude'].isna()]

print("Missing:", len(missing))

missing[['city','locality']].sample(30)

Missing: 508

           city                         locality
395   bengaluru                     Srinivaspura
2186       pune                   Salisbury Park
889     chennai                      Maduravayal
1688    kolkata                         Omarhati
1826    kolkata                         Satpukur
1217      delhi                     Shakur Basti
857     chennai                       Natthamedu
440   bengaluru                    Kasuvanahalli
1624  hyderabad                    Madanna Gudem
1912     mumbai                          Saphale
2166       pune                           Bhivri
877     chennai                   Karayanchavadi
1619  hyderabad                        Umdanagar
1614  hyderabad                   Brahmana Pally
645     chennai                  Thirumudivakkam
928     chennai                     Tirupandiyur
1469  hyderabad                      Madeenaguda
1171      delhi                        Tri Nagar
185   bengaluru     Uttarahalli -Manavarthekaval
1442  hyderabad                        Majarguda
846     chennai                       Agaramthen
2140       pune                    Charholi Kurd
1418  hyderabad                           Kollur
1602  hyderabad                     Nagarkurnool
1141      delhi                 Ranhola Extesion
369   bengaluru  BEML Cooperative Society Layout
1441  hyderabad              Hyderabad Shah Guda
508   bengaluru                       Kithiganur
835     chennai                    Ottiyambakkam
1696    kolkata                        Bramhapur

In [24]:
missing = cor[cor['latitude'].isna()]

print(

    missing.groupby('city')

    .size()

)

city
ahmedabad     33
bengaluru    117
chennai      132
delhi         22
gurgaon        6
hyderabad     79
kolkata       66
mumbai        18
pune          35
dtype: int64

In [25]:
cor = cor.dropna(
    subset=['latitude','longitude']
)

In [26]:
cor.to_csv(
    "data/coordinates.csv", index=False)

In [27]:
avg_price = (

    df.groupby(

        ['city','locality']

    )['price_cr']

    .mean()

    .reset_index()

)


map_df = avg_price.merge(

    cor,

    on=['city','locality'],

    how='inner'

)